name: Deploying Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
            
      - name: Install NPM packages
        run: npm install
      
      - name: Setup .env
        run: echo Setting up env variables
        env:
          psqlUser=${{secrets.psqlUser}}
          psqlHost=${{secrets.psqlHost}}
          psqlName=${{secrets.psqlName}}
          psqlPass=${{secrets.psqlPass}}
          psqlPort=5432
          AWSS3ID=${{secrets.AWSS3ID}}
          AWSS3SECRET=${{secrets.AWSS3SECRET}}
          PORT=3000
          HOST=0.0.0.0
          COOKIE_SECRET=${{secrets.AWSS3SECRET}}
          REFRESH_TOKEN_SECRET=${{secrets.REFRESH_TOKEN_SECRET}}
          ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}}
          GIT_SECRET=${{secrets.GIT_SECRET}}
          GIT_CLIENT=${{secrets.GIT_CLIENT}}

        
      - name: Run prettier check
        run: npm run prettier:check

      - name: Run Lint check
        run: npm run tslint

      - name: Run Unit testing
        run: npm run test:actionEnv

      - name: Run production build
        run: npm run build
        
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: sh /home/ubuntu/workbattle-backend/ci-cd-scripts/pull-deploy-dev.sh
